name: edna_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  uuid: ^4.3.3
  zoom_tap_animation: ^1.1.0
  google_generative_ai: ^0.2.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  mime: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/edna_logo.jpeg"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/edna_logo.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/edna_logo.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/edna_logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/


flutter_native_splash:
  color: "#006878"
  fullscreen: false
  android_gravity: fill
  ios_content_mode: scaleToFill
  web_image_mode: cover
