name: edna_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  file_picker: ^5.3.3
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  go_router: ^10.1.0
  google_fonts: ^4.0.4
  google_generative_language_api: ^0.1.2
  http: ^0.13.6
  image_picker: ^1.0.2
  intl: ^0.18.1
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
