name: edna_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  uuid: ^4.0.0-beta3-1
  path: ^1.8.3
  zoom_tap_animation: ^1.1.0
  palm_api: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
